// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Booking is the predicate function for booking builders.
type Booking func(*sql.Selector)

// Bookingtype is the predicate function for bookingtype builders.
type Bookingtype func(*sql.Selector)

// ClientEntity is the predicate function for cliententity builders.
type ClientEntity func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
