// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/B6111427/app/ent/booking"
	"github.com/B6111427/app/ent/bookingtype"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// BookingtypeCreate is the builder for creating a Bookingtype entity.
type BookingtypeCreate struct {
	config
	mutation *BookingtypeMutation
	hooks    []Hook
}

// SetBOOKTYPENAME sets the BOOKTYPE_NAME field.
func (bc *BookingtypeCreate) SetBOOKTYPENAME(s string) *BookingtypeCreate {
	bc.mutation.SetBOOKTYPENAME(s)
	return bc
}

// AddBooktypeIDs adds the booktype edge to Booking by ids.
func (bc *BookingtypeCreate) AddBooktypeIDs(ids ...int) *BookingtypeCreate {
	bc.mutation.AddBooktypeIDs(ids...)
	return bc
}

// AddBooktype adds the booktype edges to Booking.
func (bc *BookingtypeCreate) AddBooktype(b ...*Booking) *BookingtypeCreate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return bc.AddBooktypeIDs(ids...)
}

// Mutation returns the BookingtypeMutation object of the builder.
func (bc *BookingtypeCreate) Mutation() *BookingtypeMutation {
	return bc.mutation
}

// Save creates the Bookingtype in the database.
func (bc *BookingtypeCreate) Save(ctx context.Context) (*Bookingtype, error) {
	if _, ok := bc.mutation.BOOKTYPENAME(); !ok {
		return nil, &ValidationError{Name: "BOOKTYPE_NAME", err: errors.New("ent: missing required field \"BOOKTYPE_NAME\"")}
	}
	if v, ok := bc.mutation.BOOKTYPENAME(); ok {
		if err := bookingtype.BOOKTYPENAMEValidator(v); err != nil {
			return nil, &ValidationError{Name: "BOOKTYPE_NAME", err: fmt.Errorf("ent: validator failed for field \"BOOKTYPE_NAME\": %w", err)}
		}
	}
	var (
		err  error
		node *Bookingtype
	)
	if len(bc.hooks) == 0 {
		node, err = bc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BookingtypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			bc.mutation = mutation
			node, err = bc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(bc.hooks) - 1; i >= 0; i-- {
			mut = bc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (bc *BookingtypeCreate) SaveX(ctx context.Context) *Bookingtype {
	v, err := bc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (bc *BookingtypeCreate) sqlSave(ctx context.Context) (*Bookingtype, error) {
	b, _spec := bc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	b.ID = int(id)
	return b, nil
}

func (bc *BookingtypeCreate) createSpec() (*Bookingtype, *sqlgraph.CreateSpec) {
	var (
		b     = &Bookingtype{config: bc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: bookingtype.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: bookingtype.FieldID,
			},
		}
	)
	if value, ok := bc.mutation.BOOKTYPENAME(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: bookingtype.FieldBOOKTYPENAME,
		})
		b.BOOKTYPENAME = value
	}
	if nodes := bc.mutation.BooktypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bookingtype.BooktypeTable,
			Columns: []string{bookingtype.BooktypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: booking.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return b, _spec
}
