// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/B6111427/app/ent/booking"
	"github.com/B6111427/app/ent/bookingtype"
	"github.com/B6111427/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// BookingtypeUpdate is the builder for updating Bookingtype entities.
type BookingtypeUpdate struct {
	config
	hooks      []Hook
	mutation   *BookingtypeMutation
	predicates []predicate.Bookingtype
}

// Where adds a new predicate for the builder.
func (bu *BookingtypeUpdate) Where(ps ...predicate.Bookingtype) *BookingtypeUpdate {
	bu.predicates = append(bu.predicates, ps...)
	return bu
}

// SetBOOKTYPENAME sets the BOOKTYPE_NAME field.
func (bu *BookingtypeUpdate) SetBOOKTYPENAME(s string) *BookingtypeUpdate {
	bu.mutation.SetBOOKTYPENAME(s)
	return bu
}

// AddBooktypeIDs adds the booktype edge to Booking by ids.
func (bu *BookingtypeUpdate) AddBooktypeIDs(ids ...int) *BookingtypeUpdate {
	bu.mutation.AddBooktypeIDs(ids...)
	return bu
}

// AddBooktype adds the booktype edges to Booking.
func (bu *BookingtypeUpdate) AddBooktype(b ...*Booking) *BookingtypeUpdate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return bu.AddBooktypeIDs(ids...)
}

// Mutation returns the BookingtypeMutation object of the builder.
func (bu *BookingtypeUpdate) Mutation() *BookingtypeMutation {
	return bu.mutation
}

// RemoveBooktypeIDs removes the booktype edge to Booking by ids.
func (bu *BookingtypeUpdate) RemoveBooktypeIDs(ids ...int) *BookingtypeUpdate {
	bu.mutation.RemoveBooktypeIDs(ids...)
	return bu
}

// RemoveBooktype removes booktype edges to Booking.
func (bu *BookingtypeUpdate) RemoveBooktype(b ...*Booking) *BookingtypeUpdate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return bu.RemoveBooktypeIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (bu *BookingtypeUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := bu.mutation.BOOKTYPENAME(); ok {
		if err := bookingtype.BOOKTYPENAMEValidator(v); err != nil {
			return 0, &ValidationError{Name: "BOOKTYPE_NAME", err: fmt.Errorf("ent: validator failed for field \"BOOKTYPE_NAME\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(bu.hooks) == 0 {
		affected, err = bu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BookingtypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			bu.mutation = mutation
			affected, err = bu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(bu.hooks) - 1; i >= 0; i-- {
			mut = bu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (bu *BookingtypeUpdate) SaveX(ctx context.Context) int {
	affected, err := bu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bu *BookingtypeUpdate) Exec(ctx context.Context) error {
	_, err := bu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bu *BookingtypeUpdate) ExecX(ctx context.Context) {
	if err := bu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (bu *BookingtypeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   bookingtype.Table,
			Columns: bookingtype.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: bookingtype.FieldID,
			},
		},
	}
	if ps := bu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bu.mutation.BOOKTYPENAME(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: bookingtype.FieldBOOKTYPENAME,
		})
	}
	if nodes := bu.mutation.RemovedBooktypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bookingtype.BooktypeTable,
			Columns: []string{bookingtype.BooktypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: booking.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.BooktypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bookingtype.BooktypeTable,
			Columns: []string{bookingtype.BooktypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: booking.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bookingtype.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// BookingtypeUpdateOne is the builder for updating a single Bookingtype entity.
type BookingtypeUpdateOne struct {
	config
	hooks    []Hook
	mutation *BookingtypeMutation
}

// SetBOOKTYPENAME sets the BOOKTYPE_NAME field.
func (buo *BookingtypeUpdateOne) SetBOOKTYPENAME(s string) *BookingtypeUpdateOne {
	buo.mutation.SetBOOKTYPENAME(s)
	return buo
}

// AddBooktypeIDs adds the booktype edge to Booking by ids.
func (buo *BookingtypeUpdateOne) AddBooktypeIDs(ids ...int) *BookingtypeUpdateOne {
	buo.mutation.AddBooktypeIDs(ids...)
	return buo
}

// AddBooktype adds the booktype edges to Booking.
func (buo *BookingtypeUpdateOne) AddBooktype(b ...*Booking) *BookingtypeUpdateOne {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return buo.AddBooktypeIDs(ids...)
}

// Mutation returns the BookingtypeMutation object of the builder.
func (buo *BookingtypeUpdateOne) Mutation() *BookingtypeMutation {
	return buo.mutation
}

// RemoveBooktypeIDs removes the booktype edge to Booking by ids.
func (buo *BookingtypeUpdateOne) RemoveBooktypeIDs(ids ...int) *BookingtypeUpdateOne {
	buo.mutation.RemoveBooktypeIDs(ids...)
	return buo
}

// RemoveBooktype removes booktype edges to Booking.
func (buo *BookingtypeUpdateOne) RemoveBooktype(b ...*Booking) *BookingtypeUpdateOne {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return buo.RemoveBooktypeIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (buo *BookingtypeUpdateOne) Save(ctx context.Context) (*Bookingtype, error) {
	if v, ok := buo.mutation.BOOKTYPENAME(); ok {
		if err := bookingtype.BOOKTYPENAMEValidator(v); err != nil {
			return nil, &ValidationError{Name: "BOOKTYPE_NAME", err: fmt.Errorf("ent: validator failed for field \"BOOKTYPE_NAME\": %w", err)}
		}
	}

	var (
		err  error
		node *Bookingtype
	)
	if len(buo.hooks) == 0 {
		node, err = buo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BookingtypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			buo.mutation = mutation
			node, err = buo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(buo.hooks) - 1; i >= 0; i-- {
			mut = buo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, buo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (buo *BookingtypeUpdateOne) SaveX(ctx context.Context) *Bookingtype {
	b, err := buo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return b
}

// Exec executes the query on the entity.
func (buo *BookingtypeUpdateOne) Exec(ctx context.Context) error {
	_, err := buo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (buo *BookingtypeUpdateOne) ExecX(ctx context.Context) {
	if err := buo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (buo *BookingtypeUpdateOne) sqlSave(ctx context.Context) (b *Bookingtype, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   bookingtype.Table,
			Columns: bookingtype.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: bookingtype.FieldID,
			},
		},
	}
	id, ok := buo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Bookingtype.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := buo.mutation.BOOKTYPENAME(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: bookingtype.FieldBOOKTYPENAME,
		})
	}
	if nodes := buo.mutation.RemovedBooktypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bookingtype.BooktypeTable,
			Columns: []string{bookingtype.BooktypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: booking.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.BooktypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bookingtype.BooktypeTable,
			Columns: []string{bookingtype.BooktypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: booking.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	b = &Bookingtype{config: buo.config}
	_spec.Assign = b.assignValues
	_spec.ScanValues = b.scanValues()
	if err = sqlgraph.UpdateNode(ctx, buo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bookingtype.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return b, nil
}
