/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersBooking
 */
export interface ControllersBooking {
    /**
     * 
     * @type {string}
     * @memberof ControllersBooking
     */
    bookingDate?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersBooking
     */
    bookingtype?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersBooking
     */
    client?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersBooking
     */
    timeLeft?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersBooking
     */
    user?: number;
}

export function ControllersBookingFromJSON(json: any): ControllersBooking {
    return ControllersBookingFromJSONTyped(json, false);
}

export function ControllersBookingFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersBooking {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bookingDate': !exists(json, 'bookingDate') ? undefined : json['bookingDate'],
        'bookingtype': !exists(json, 'bookingtype') ? undefined : json['bookingtype'],
        'client': !exists(json, 'client') ? undefined : json['client'],
        'timeLeft': !exists(json, 'timeLeft') ? undefined : json['timeLeft'],
        'user': !exists(json, 'user') ? undefined : json['user'],
    };
}

export function ControllersBookingToJSON(value?: ControllersBooking | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bookingDate': value.bookingDate,
        'bookingtype': value.bookingtype,
        'client': value.client,
        'timeLeft': value.timeLeft,
        'user': value.user,
    };
}


