/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntBooking,
    EntBookingFromJSON,
    EntBookingFromJSONTyped,
    EntBookingToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntBookingtypeEdges
 */
export interface EntBookingtypeEdges {
    /**
     * Booktype holds the value of the booktype edge.
     * @type {Array<EntBooking>}
     * @memberof EntBookingtypeEdges
     */
    booktype?: Array<EntBooking>;
}

export function EntBookingtypeEdgesFromJSON(json: any): EntBookingtypeEdges {
    return EntBookingtypeEdgesFromJSONTyped(json, false);
}

export function EntBookingtypeEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntBookingtypeEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'booktype': !exists(json, 'booktype') ? undefined : ((json['booktype'] as Array<any>).map(EntBookingFromJSON)),
    };
}

export function EntBookingtypeEdgesToJSON(value?: EntBookingtypeEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'booktype': value.booktype === undefined ? undefined : ((value.booktype as Array<any>).map(EntBookingToJSON)),
    };
}


