/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntBookingtypeEdges,
    EntBookingtypeEdgesFromJSON,
    EntBookingtypeEdgesFromJSONTyped,
    EntBookingtypeEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntBookingtype
 */
export interface EntBookingtype {
    /**
     * BOOKTYPENAME holds the value of the "BOOKTYPE_NAME" field.
     * @type {string}
     * @memberof EntBookingtype
     */
    bOOKTYPENAME?: string;
    /**
     * 
     * @type {EntBookingtypeEdges}
     * @memberof EntBookingtype
     */
    edges?: EntBookingtypeEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntBookingtype
     */
    id?: number;
}

export function EntBookingtypeFromJSON(json: any): EntBookingtype {
    return EntBookingtypeFromJSONTyped(json, false);
}

export function EntBookingtypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntBookingtype {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bOOKTYPENAME': !exists(json, 'BOOKTYPE_NAME') ? undefined : json['BOOKTYPE_NAME'],
        'edges': !exists(json, 'edges') ? undefined : EntBookingtypeEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntBookingtypeToJSON(value?: EntBookingtype | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'BOOKTYPE_NAME': value.bOOKTYPENAME,
        'edges': EntBookingtypeEdgesToJSON(value.edges),
        'id': value.id,
    };
}


