/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntBooking,
    EntBookingFromJSON,
    EntBookingFromJSONTyped,
    EntBookingToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntClientEntityEdges
 */
export interface EntClientEntityEdges {
    /**
     * Booked holds the value of the booked edge.
     * @type {Array<EntBooking>}
     * @memberof EntClientEntityEdges
     */
    booked?: Array<EntBooking>;
}

export function EntClientEntityEdgesFromJSON(json: any): EntClientEntityEdges {
    return EntClientEntityEdgesFromJSONTyped(json, false);
}

export function EntClientEntityEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntClientEntityEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'booked': !exists(json, 'booked') ? undefined : ((json['booked'] as Array<any>).map(EntBookingFromJSON)),
    };
}

export function EntClientEntityEdgesToJSON(value?: EntClientEntityEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'booked': value.booked === undefined ? undefined : ((value.booked as Array<any>).map(EntBookingToJSON)),
    };
}


