/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntBooking,
    EntBookingFromJSON,
    EntBookingFromJSONTyped,
    EntBookingToJSON,
    EntRole,
    EntRoleFromJSON,
    EntRoleFromJSONTyped,
    EntRoleToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntUserEdges
 */
export interface EntUserEdges {
    /**
     * Booking holds the value of the booking edge.
     * @type {Array<EntBooking>}
     * @memberof EntUserEdges
     */
    booking?: Array<EntBooking>;
    /**
     * 
     * @type {EntRole}
     * @memberof EntUserEdges
     */
    roleplay?: EntRole;
}

export function EntUserEdgesFromJSON(json: any): EntUserEdges {
    return EntUserEdgesFromJSONTyped(json, false);
}

export function EntUserEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntUserEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'booking': !exists(json, 'booking') ? undefined : ((json['booking'] as Array<any>).map(EntBookingFromJSON)),
        'roleplay': !exists(json, 'roleplay') ? undefined : EntRoleFromJSON(json['roleplay']),
    };
}

export function EntUserEdgesToJSON(value?: EntUserEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'booking': value.booking === undefined ? undefined : ((value.booking as Array<any>).map(EntBookingToJSON)),
        'roleplay': EntRoleToJSON(value.roleplay),
    };
}


