// Code generated by entc, DO NOT EDIT.

package cliententity

const (
	// Label holds the string label denoting the cliententity type in the database.
	Label = "client_entity"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCLIENTNAME holds the string denoting the client_name field in the database.
	FieldCLIENTNAME = "client_name"
	// FieldCLIENTSTATUS holds the string denoting the client_status field in the database.
	FieldCLIENTSTATUS = "client_status"

	// EdgeBooked holds the string denoting the booked edge name in mutations.
	EdgeBooked = "booked"

	// Table holds the table name of the cliententity in the database.
	Table = "client_entities"
	// BookedTable is the table the holds the booked relation/edge.
	BookedTable = "bookings"
	// BookedInverseTable is the table name for the Booking entity.
	// It exists in this package in order to avoid circular dependency with the "booking" package.
	BookedInverseTable = "bookings"
	// BookedColumn is the table column denoting the booked relation/edge.
	BookedColumn = "CLIENT_ID"
)

// Columns holds all SQL columns for cliententity fields.
var Columns = []string{
	FieldID,
	FieldCLIENTNAME,
	FieldCLIENTSTATUS,
}

var (
	// CLIENTNAMEValidator is a validator for the "CLIENT_NAME" field. It is called by the builders before save.
	CLIENTNAMEValidator func(string) error
	// CLIENTSTATUSValidator is a validator for the "CLIENT_STATUS" field. It is called by the builders before save.
	CLIENTSTATUSValidator func(string) error
)
